apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xwlfx76dg-nodejs 
  janus-idp.io/tekton: xwlfx76dg-nodejs
  backstage.io/kubernetes-id: xwlfx76dg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xwlfx76dg-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml