apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xwlfx76dg-nodejs
  janus-idp.io/tekton: xwlfx76dg-nodejs
  backstage.io/kubernetes-id: xwlfx76dg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xwlfx76dg-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
