apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xwlfx76dg-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xwlfx76dg-nodejs 
  name: xwlfx76dg-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: xwlfx76dg-nodejs 
